### ISSUE TITLE
sbt.scala

### ISSUE THREAD

**Issue by ironfish** [derekwyatt/vim-scala#107]
`au BufRead,BufNewFile *.sbt setfiletype sbt.scala` in `fdetect/scala.vim` causes all `.sbt` files to be picked up by [syntastic](https://github.com/scrooloose/syntastic). You might want to add the following to your `README.md` to get around this:

If you use `syntastic` it will pick up `.sbt` files for checking. To get around this, add the following to your `.vimrc`:

```vim
" SBT
" required to disable syntastic checking.
augroup filetype_sbt
  autocmd!
  autocmd BufNewFile,BufRead *.sbt set filetype=sbt
  autocmd FileType sbt setlocal syntax=scala
augroup END
```

**Comment by ches** [comment]
Thank you for the suggestion.

I've just configured Syntastic to simply ignore `.sbt` files. Setting `filetype` to `sbt` and `syntax` to `scala` might be an alternative we could consider, but part of the reason for the current dotted filetype approach was that some people will have [vim-sbt][1] installed, others won't. The dotted filetype mostly works out well in either case (see #54).

Generally speaking, I don't think it's our job to document how to use other plugins—people using them should, well, understand how to use them. Otherwise, where does it stop? Customizing filetype behaviors is probably one of the most common things Syntastic users will configure for it (and indeed for Scala it defaults to active checks using both `scalac` and `fsc` checkers IIRC, which is annoyingly slow to me, so I immediately customized the settings).

That said, if we can have better defaults that are more friendly to users of other plugins without detriment to people who don't use them, I'm all for that, if reasoning convinces everyone. It also might make sense to just include vim-sbt into vim-scala—I'll leave that to @derekwyatt, he may have reasons for not doing so already.

The above suggestion, if I'm thinking about it correctly, would result in vim-sbt users not seeing the additional syntax highlighting that plugin provides, or at best it would be load order-dependent. It also would mean that some things like Scala snippets from snippet plugins no longer work in sbt files, but that could be easily fixed for plugins that support an "include" feature to use the snippets of multiple filetypes together, and that might even be the "right" approach. UltiSnips can do this, but I'm not sure if Snipmate or xptemplate can, so open to suggestions on that.

[1]: https://github.com/derekwyatt/vim-sbt

**Comment by ches** [comment]
My relevant Syntastic settings, in case anyone is curious:

```vim
let g:syntastic_ignore_files = ['\m\c\.h$', '\m\.sbt$']

" Scala has fsc and scalac checkers--running both is pretty redundant and
" slow. An explicit `:SyntasticCheck scalac` can always run the other.
let g:syntastic_scala_checkers = ['fsc']
```

Perhaps the wiki of this repo would be a good place for configuration tips for a nice Scala editing experience in Vim, beyond vim-scala. That way users can easily contribute without the friction of pull requests for README changes.

**Comment by ironfish** [comment]
Hi @ches 

I think the wiki would be an excellent place for this kind of stuff.

Thanks for your input.
