### ISSUE TITLE
Syntax Highlighting in Pattern Matching

### ISSUE THREAD

**Issue by benknoble** [derekwyatt/vim-scala#134]
<img width="426" alt="screen shot 2016-11-04 at 5 14 56 pm" src="https://cloud.githubusercontent.com/assets/22802209/20022748/5e31d35a-a2b2-11e6-8c26-6b7004f6c60d.png">

Just look at it. You'll notice that _some_ of the cases have pink highlights, but in particular on the line
```scala
a :: tail => //...
```
the `tail` is the color of my terminals text (green); i.e., it isn't highlighted. Can we fix this?

**Comment by derekwyatt** [comment]
I claim that the bug here is more that `a` is not green.  Let's take an example:
```
case Seq(a, b, 1, 4, List(x, y)) =>
```
Should that all be pink?  I think not because it's diminishing the value of the highlighting, in general.  Certainly, `1` and `4` should be highlighted as numbers.

But, at any rate, the issue should be filed in the [Vim](https://github.com/vim/vim) project instead, since the core part of this plugin has been moved there.
