### ISSUE TITLE
Alternative solution for ftplugin

### ISSUE THREAD

**Issue by char101** [derekwyatt/vim-scala#49]
Hi,

Instead of removing the default values of tabstop, etc. from ftplugin, I suggest instead to add a global variable that can be set by the user in the vimrc. Maybe something like this:

```viml
if !exists('g:vim_scala_own_settings') || !g:vim_scala_own_settings
  setlocal textwidth=140
  setlocal shiftwidth=2
  setlocal softtabstop=2
  setlocal expandtab
  setlocal formatoptions=tcqr
endif
```

Thanks.

**Comment by ivan-cukic** [comment]
after/ftplugin/scala.vim is not a solution, at least, it does not work for me. Indent from scala-vim is evaluated after after/ftplugin/scala.vim which can easily be tested by putting echoes in both of them.

It prints out:

```
This is after/ftplugin
This is scala-vim
```

**Comment by char101** [comment]
@ivan-cukic Have you tried with `after/indent/scala.vim`?

**Comment by ivan-cukic** [comment]
after/indent/ works.

Still, I don't quite get the reasoning for this to be in the indent file. The only indentation specification that does this in vim's default package is ada, with clojure srtting the softtabstop.

**Comment by ches** [comment]
I'd agree the tab settings aren't typically in the indent files, changed in 1f90f5e.

Re: the original issue suggestion, `after/ftplugin/scala.vim` is definitely the usual way to achieve this, and/or `autocmd FileType scala` if it's small stuff you'd keep in vimrc instead of more files. These should both now be possible following the change.

I think that makes everyone happy here, so closing.
